services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5433:5432"
    networks:
      - backend
    # this would permamanetly store the data in the host machine
    # volumes:
    #   - ./data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
